### ISSUE TITLE
Support resource metadata 

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/modelx#1]
在初始化模型目录时，添加模型运行的基本预估资源参数，可用于在模型商店中展示和快速填充

```
config:
  inputs: {}
  outputs: {}
  resource:
    cpu: "4"
    memory: "16Gi"
    gpu:
      nvidia:
        nvidia/gpu: "1"
      gpu-manager:
        tencent.com/vcuda-core: '50'
        tencent.com/vcuda-memory: '25'
```
